---
title: "hex_sticker"
format: html
---

```{r}
library(hexSticker)
library(tidyverse)
library(sicegar)
```

```{r}
# wes colors
"#FF0000"
"#00A08A"
"#F2AD00"
"#F98400"
"#5BBCD6"
```


# sicegar

```{r}
# --- Simulate sigmoidal data ---
use_h0 <- FALSE
noise_parameter <- 0.3
reps <- 5
time <- seq(0, 24, 3)

mean_vals <- rep(
  sigmoidalFitFormula_h0(time,
                         maximum = 4,
                         slopeParam = 1,
                         midPoint = 12,
                         h0 = 3),
  reps
)

intensity <- rnorm(
  n = length(mean_vals),
  mean = mean_vals,
  sd = rep(noise_parameter, length(mean_vals))
)

dataInput <- data.frame(intensity = intensity, time = rep(time, reps))

# --- Fit the sigmoid curve ---
sig_fit <- fitAndCategorize(dataInput, use_h0 = TRUE,)

# --- Generate fitted curve for plotting ---
fit_data <- data.frame(
  time,
  fitted = sigmoidalFitFormula_h0(
    time,
    maximum = sig_fit$sigmoidalModel$maximum_Estimate,
    slopeParam = sig_fit$sigmoidalModel$slopeParam_Estimate,
    midPoint = sig_fit$sigmoidalModel$midPoint_Estimate,
    h0 = sig_fit$sigmoidalModel$h0_Estimate
  )
)

# --- Make the ggplot (subplot for sticker) ---
sig_plot <- ggplot(dataInput, aes(x = time, y = intensity)) +
  geom_point(color = "white", size = 1.2, alpha = 0.7) +
  geom_line(data = fit_data, aes(y = fitted), color = "#E27D60", size = 1) +
  theme_void() +
  theme_transparent()  # remove background, clean look for sticker

# --- Create sticker ---
s <- sticker(
  sig_plot,
  package = "sicegar",
  p_size = 20,
  s_x = 1,
  s_y = 0.75,
  s_width = 1.3,
  s_height = 0.9,
  filename = "sigmoidal_curve_sticker.png"
)

plot(s)



```

```{r}
use_h0 <- TRUE
noise_parameter <- 0.25
reps <- 5
time <- seq(0, 24, 3)

mean_vals <- rep(
  sigmoidalFitFormula_h0(time,
                         maximum = 4,
                         slopeParam = 1,
                         midPoint = 12,
                         h0 = 3),
  reps
)

intensity <- rnorm(
  n = length(mean_vals),
  mean = mean_vals,
  sd = rep(noise_parameter, length(mean_vals))
)

dataInput <- data.frame(intensity = intensity, time = rep(time, reps))

dataInput |>
  ggplot(aes(x = time, y = intensity)) +
  geom_point()
```


# Me

```{r}
library(hexSticker)
library(magick)

img <- image_read("Images/head_shot_hex.jpeg") |>
  image_resize("2000x2000^") |>
  image_crop("2000x2000")

hex_mask <- image_blank(2000, 2000, color = "transparent") |>
  image_draw()
polygon(
  x = c(1000, 1850, 1850, 1000, 150, 150),
  y = c(0, 500, 1500, 2000, 1500, 500),
  col = "white", border = NA
)
dev.off()

hex_img <- image_composite(img, hex_mask, operator = "copyopacity")

# IMPORTANT: force PNG output
image_write(hex_img, path = "headshot_hex_masked.png", format = "png")


# make sticker
me <- sticker(
  subplot  = "headshot_hex_masked.png",
  package  = "",
  s_x      = 1, s_y = 1,
  s_width  = 1, s_height = 1,
  h_color = "#F2AD00",
  filename = "hex-face.png",
  dpi      = 800
)

plot(me)

```

# research

```{r}
library(sicegar)
library(tidyverse)
# --- Simulate sigmoidal data ---
use_h0 <- FALSE
noise_parameter <- 0.2
reps <- 5
time <- seq(0, 24, 3)

mean_vals <- rep(
  sigmoidalFitFormula_h0(time,
                         maximum = 4,
                         slopeParam = 1,
                         midPoint = 12,
                         h0 = 3),
  reps
)

intensity <- rnorm(
  n = length(mean_vals),
  mean = mean_vals,
  sd = rep(noise_parameter, length(mean_vals))
)

dataInput <- data.frame(intensity = intensity, time = rep(time, reps))

# --- Fit the sigmoid curve ---
sig_fit <- fitAndCategorize(dataInput, use_h0 = TRUE,)

# --- Generate fitted curve for plotting ---
fit_data <- data.frame(
  time,
  fitted = sigmoidalFitFormula_h0(
    time,
    maximum = sig_fit$sigmoidalModel$maximum_Estimate,
    slopeParam = sig_fit$sigmoidalModel$slopeParam_Estimate,
    midPoint = sig_fit$sigmoidalModel$midPoint_Estimate,
    h0 = sig_fit$sigmoidalModel$h0_Estimate
  )
)

# --- Make the ggplot (subplot for sticker) ---
sig_plot <- ggplot(dataInput, aes(x = time, y = intensity)) +
  geom_point(color = "white", size = 1.2, alpha = 0.7) +
  geom_line(data = fit_data, aes(y = fitted), color = "#F98400", size = 1) +
  theme_void() +
  theme_transparent()  # remove background, clean look for sticker

# --- Create sticker ---
s <- sticker(
  sig_plot,
  package = "Research",
  p_size = 20,
  s_x = 1,
  s_y = 0.75,
  s_width = 1.3,
  s_height = 0.9,,
  h_fill   = "#5BBCD6",   # background color
  h_color  = "#00A08A",   # outline color
  filename = "hex-research.png"
)

plot(s)

```

# about

```{r}
about <- sticker(
  subplot  = "Images/liberty_bell.png",
  package  = "About me",
  p_size   = 36,
  s_x      = 1,
  s_y      = 0.75,
  s_width  = 0.45,
  h_fill   = "#00A08A",   # background color
  h_color  = "#FF0000",   # outline color
  filename = "hex-about.png",
  dpi      = 600
)

plot(about)


```

# data viz

```{r}
data_viz <- sticker(
  subplot  = "Images/us_map.png",
  package  = "Data Viz",
  p_size   = 36,
  s_x      = 1,
  s_y      = 0.75,
  s_width  = 0.55,
  h_fill   = "#F2AD00",   # background color
  h_color  = "#FF0000",   # outline color
  filename = "hex-data_viz.png",
  dpi      = 600
)

plot(data_viz)
```

# colleges

```{r}
college <- sticker(
  subplot  = "Images/class.png",
  package  = "Comp Stats Project",
  p_size   = 28,
  s_x      = 1,
  s_y      = 0.75,
  s_width  = 0.35,
  h_fill   = "#FF0000",   # background color
  h_color  = "#5BBCD6",   # outline color
  filename = "hex-class_project.png",
  dpi      = 600
)

plot(college)
```
```






