---
title: "Eclipse 4/9/24"
format: html
editor: source
execute: 
  warning: false
  message: false

project:
  type: website
  output-dir: docs
  
---

```{r}
library(tidyverse)
library(patchwork)
library(praise)
```


## the data

This data has information about the paths of the solar eclipses on October 14, 2023 and April 8, 2024 in the United States. The data comes from NASA's Scientific Visualization Studio.

```{r}
eclipse_annular_2023 <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-04-09/eclipse_annular_2023.csv')
eclipse_total_2024 <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-04-09/eclipse_total_2024.csv')
eclipse_partial_2023 <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-04-09/eclipse_partial_2023.csv')
eclipse_partial_2024 <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-04-09/eclipse_partial_2024.csv')

```

## maps

```{r}
# tidy 2024 data
tot_24 <- eclipse_total_2024 %>% 
  mutate(time = eclipse_6 - eclipse_1, eclipse = "total") %>% 
  select(state, name, lat, lon, time, eclipse)

part_24 <- eclipse_partial_2024 %>% 
  mutate(time = eclipse_5 - eclipse_1, eclipse = "partial") %>% 
  select(state, name, lat, lon, time, eclipse)

eclipse_24 <- rbind(tot_24, part_24) %>% 
  mutate(time = as.numeric(time))

```

```{r}
# plot 2024 data
library(ggnewscale)
states <- map_data("state")

twenty_four <- ggplot(states) +
  geom_polygon(fill = "white", color = "black",
               aes(long,lat, group = group)) +
  geom_point(data = filter(eclipse_24, lat < 51 & lat > 24 & lon < 0 & eclipse == "total"), 
             aes(x = lon, y= lat, color = time), size = 0.001) +
  scale_colour_gradientn(colors = c("blue", "turquoise")) +
  labs(color = "time of overlap (sec)\n total eclipse") +
  new_scale_color() +
  geom_point(data = filter(eclipse_24, lat < 51 & lat > 24 & lon < 0 & eclipse == "partial"), 
             aes(x = lon, y= lat, color = time), size = 0.001) +
  scale_colour_gradientn(colors = c("red", "pink")) +
  ggtitle("2024 Solar Eclipse") +
  labs(x = "", y = "", color = "time of overlap (sec)\n partial eclipse")
  
```

```{r}
# tidy 2023 data
tot_23 <- eclipse_annular_2023 %>% 
  mutate(time = eclipse_6 - eclipse_1, eclipse = "total") %>% 
  select(state, name, lat, lon, time, eclipse)

part_23 <- eclipse_partial_2023 %>% 
  mutate(time = eclipse_5 - eclipse_1, eclipse = "partial") %>% 
  select(state, name, lat, lon, time, eclipse)

eclipse_23 <- rbind(tot_23, part_23) %>% 
  mutate(time = as.numeric(time))
```

```{r}
# plot 2023 data
states <- map_data("state")

twenty_three <- ggplot(states) +
  geom_polygon(fill = "white", color = "black",
               aes(long,lat, group = group)) +
  geom_point(data = filter(eclipse_23, lat < 51 & lat > 24 & lon < 0 & eclipse == "total"), 
             aes(x = lon, y= lat, color = time), size = 0.25) +
  scale_colour_gradientn(colors = c("blue", "turquoise")) +
  labs(color = "time of overlap (sec)\n total eclipse") +
  new_scale_color() +
  geom_point(data = filter(eclipse_23, lat < 51 & lat > 24 & lon < 0 & eclipse == "partial"), 
             aes(x = lon, y= lat, color = time), size = 0.001) +
  scale_colour_gradientn(colors = c("red", "pink")) +
  ggtitle("2023 Solar Eclipse") +
  labs(x = "", y = "", color = "time of overlap (sec)\n partial eclipse")
  
```

```{r, fig.width=12, fig.height=5}
twenty_three + twenty_four + plot_layout(ncol = 2)
```










